function [sigAudio, noiseAudio, t, instFreq] = makeSRWUpcall(sampleRate, noiseRMS)
% Generate a synthetic Southern Right Whale upcall for testing.
%
% The upcall follows a quadratic instantaneous frequency sweep:
%   f(t) = 80 + 118*t^2  Hz
%
% which starts at 80 Hz and reaches ~198 Hz at t = 1 s. This matches
% the characteristic SRW upcall contour described in Miller et al.
%
% The audio is generated by integrating the instantaneous frequency to
% obtain the phase argument of the sine wave:
%   x(t) = sin(2*pi * integral(f(t))) = sin(2*pi * (80*t + 118*t^3/3))
%
% This is the correct FM synthesis approach — using sin(2*pi*f(t)*t)
% would give the wrong sweep shape for non-constant f(t).
%
% INPUTS
%   sampleRate   Sample rate in Hz (default: 1000)
%                1000 Hz gives comfortable headroom above the 200 Hz peak.
%   noiseRMS     RMS amplitude of Gaussian background noise (default: 0.1)
%
% OUTPUTS
%   sigAudio   Column vector: upcall + noise, duration = 1 s
%   noiseAudio Column vector: noise only, same length (independent draw)
%   t          Time vector in seconds
%   instFreq   Instantaneous frequency at each sample (Hz), for verification
%
% SIGNAL PARAMETERS (fixed, matching SRW upcall)
%   Duration:  1 s
%   f(t):      80 + 118*t^2  Hz
%   Freq band: [80 200] Hz
%   Amplitude: 1.0 RMS (before mixing with noise)

if nargin < 1 || isempty(sampleRate), sampleRate = 1000; end
if nargin < 2 || isempty(noiseRMS),   noiseRMS   = 0.1;  end

durSec   = 1.0;
signalRMS = 1.0;

rng(42);
nSamples = round(durSec * sampleRate);
t        = (0 : nSamples-1)' / sampleRate;

% Instantaneous frequency: f(t) = 80 + 118*t^2
instFreq = 80 + 118 * t.^2;

% Phase: integral of f(t) = 80*t + 118*t^3/3
phase = 80*t + (118/3)*t.^3;

% Generate the sweep and scale to target RMS
sweep     = sin(2 * pi * phase);
sweep     = sweep * (signalRMS / rms(sweep));

% Scale wideband noise so in-band RMS equals noiseRMS.
% Upcall sweeps ~80-198 Hz; use bandwidth ~135 Hz over Nyquist.
nyquist     = sampleRate / 2;
bandwidth   = 135;
widebandRMS = noiseRMS * sqrt(nyquist / bandwidth);
noise       = widebandRMS * randn(nSamples, 1);
sigAudio    = sweep + noise;
noiseAudio  = widebandRMS * randn(nSamples, 1);

end
