function [rmsSignal, rmsNoise, noiseVar] = snrWADA( ...
    sigAudio, noiseAudio, nfft, nOverlap, sampleRate, freq, metadata)
% Estimate SNR using the WADA-SNR algorithm (Kim & Stern 2008).
%
% WADA (Waveform Amplitude Distribution Analysis) estimates SNR from the
% amplitude distribution of the signal window alone, without requiring a
% separate noise window. It assumes:
%   (1) Clean signal follows a symmetric Gamma distribution (shaping param = 0.4)
%   (2) Background noise is Gaussian
%
% The key statistic Gz = E[ln|z|] - ln(E[|z|]) is computed from the
% bandpass-filtered signal window and mapped to SNR via a precomputed
% lookup table (Table generated by Monte Carlo integration of the joint
% gamma + Gaussian amplitude distribution, N=1e6 samples per SNR level).
%
% Note: Gz DECREASES with SNR (from ~-0.41 at -20 dB to ~-1.63 at +100 dB)
% because the gamma distribution is more peaky than Gaussian, making the
% ratio E[ln|z|]/ln(E[|z|]) more negative as signal dominates.
%
% Adapted for bioacoustics by bandpass filtering to the annotation
% frequency band before computing Gz.
%
% Reference:
%   Kim, C. & Stern, R.M. (2008). Robust Signal-to-Noise Ratio Estimation
%   Based on Waveform Amplitude Distribution Analysis. Interspeech 2008,
%   pp. 2598-2601. https://www.isca-archive.org/interspeech_2008/kim08e_interspeech.html
%
% INPUTS
%   sigAudio    Signal audio samples (column vector)
%   noiseAudio  Noise audio samples — used only for rmsNoise/noiseVar output
%   nfft        FFT length — not used; kept for interface consistency
%   nOverlap    Window overlap — not used; kept for interface consistency
%   sampleRate  Sample rate in Hz
%   freq        [lowHz highHz] bandpass filter range
%   metadata    Calibration metadata struct, or [] for no calibration
%
% OUTPUTS
%   rmsSignal  Signal power estimate (linear; uPa^2 if calibrated)
%   rmsNoise   Noise power estimate  (linear; uPa^2 if calibrated)
%   noiseVar   Variance of noise window instantaneous power

if nargin < 7, metadata = []; end

%% Precomputed Gz-to-SNR lookup table
% snrGrid_dB: -20:1:100 (121 values)
% Gz_table(i) = Gz at SNR = snrGrid_dB(i)
% Generated by Monte Carlo (N=1e6): symmetric gamma(0.4) + Gaussian noise
% Gz DECREASES monotonically with SNR.
snrGrid_dB = -20 : 1 : 100;
Gz_table = [ ...
   -0.4100  -0.4103  -0.4098  -0.4105  -0.4082  -0.4090  -0.4100  -0.4105 ...
   -0.4129  -0.4127  -0.4131  -0.4166  -0.4190  -0.4220  -0.4261  -0.4309 ...
   -0.4387  -0.4465  -0.4559  -0.4679  -0.4813  -0.4964  -0.5138  -0.5308 ...
   -0.5540  -0.5771  -0.6008  -0.6256  -0.6535  -0.6808  -0.7087  -0.7375 ...
   -0.7656  -0.7963  -0.8251  -0.8543  -0.8829  -0.9148  -0.9395  -0.9695 ...
   -0.9970  -1.0234  -1.0440  -1.0707  -1.0964  -1.1191  -1.1423  -1.1610 ...
   -1.1830  -1.2032  -1.2241  -1.2414  -1.2599  -1.2731  -1.2901  -1.3070 ...
   -1.3212  -1.3354  -1.3462  -1.3629  -1.3759  -1.3891  -1.3997  -1.4118 ...
   -1.4216  -1.4348  -1.4410  -1.4488  -1.4594  -1.4673  -1.4782  -1.4814 ...
   -1.4895  -1.5007  -1.5013  -1.5093  -1.5166  -1.5207  -1.5285  -1.5302 ...
   -1.5408  -1.5412  -1.5472  -1.5521  -1.5570  -1.5588  -1.5630  -1.5635 ...
   -1.5678  -1.5789  -1.5780  -1.5799  -1.5839  -1.5844  -1.5892  -1.5901 ...
   -1.5932  -1.5949  -1.5991  -1.6041  -1.6019  -1.6027  -1.6093  -1.6057 ...
   -1.6079  -1.6091  -1.6094  -1.6094  -1.6148  -1.6184  -1.6187  -1.6194 ...
   -1.6225  -1.6169  -1.6214  -1.6236  -1.6199  -1.6232  -1.6270  -1.6249 ...
   -1.6265 ];

%% Bandpass filter to annotation band
filterOrder = max(48, round(10 * sampleRate / diff(freq)));
filterOrder = filterOrder + mod(filterOrder, 2);
try
    d = designfilt('bandpassfir', 'FilterOrder', filterOrder, ...
        'CutoffFrequency1', freq(1), 'CutoffFrequency2', freq(2), ...
        'SampleRate', sampleRate);
    sigFilt   = filtfilt(d, sigAudio);
    noiseFilt = filtfilt(d, noiseAudio);
catch
    sigFilt   = sigAudio;
    noiseFilt = noiseAudio;
end

%% Calibration (scalar flat-band at centre frequency)
calFactor2 = 1;
if ~isempty(metadata)
    centreFq     = mean(freq);
    gainAtCentre = interp1(log10(metadata.frontEndFreq_Hz), ...
        metadata.frontEndGain_dB, log10(centreFq), 'linear', 'extrap');
    calFactor    = metadata.adPeakVolt / ...
        10^((metadata.hydroSensitivity_dB + gainAtCentre) / 20);
    calFactor2   = calFactor^2;
end

%% Compute Gz from signal window (eq. 8 of Kim & Stern 2008)
z    = sigFilt - mean(sigFilt);
z_nz = z(z ~= 0);

if numel(z_nz) < 20
    rmsSignal = nan;  rmsNoise = nan;  noiseVar = nan;
    return
end

absz = abs(z_nz);
Gz   = mean(log(absz)) - log(mean(absz));

%% Map Gz to SNR via lookup table
% Gz decreases monotonically with SNR, so flip for interp1
if Gz >= Gz_table(1)
    snr_dB = snrGrid_dB(1);      % below -20 dB
elseif Gz <= Gz_table(end)
    snr_dB = snrGrid_dB(end);    % above 100 dB
else
    % Gz_table is monotonically decreasing — flip to make it increasing
    snr_dB = interp1(flip(Gz_table), flip(snrGrid_dB), Gz, 'linear');
end

%% Derive signal and noise power from SNR and total power
snrLinear   = 10^(snr_dB / 10);
totalPower  = mean(z.^2);
noisePower  = totalPower / (snrLinear + 1);
signalPower = totalPower - noisePower;

rmsSignal = max(signalPower, 0) * calFactor2;
rmsNoise  = max(noisePower,  0) * calFactor2;

%% Noise window statistics from measured noise audio
nFilt    = noiseFilt - mean(noiseFilt);
noiseVar = var(nFilt.^2) * calFactor2^2;

% Use measured noise power if within 10 dB of WADA estimate (sanity check)
measuredNoise = mean(nFilt.^2) * calFactor2;
if measuredNoise > 0 && rmsNoise > 0 && abs(10*log10(measuredNoise/rmsNoise)) < 10
    rmsNoise = measuredNoise;
end

end
